# Generated by Django 4.0.6 on 2022-07-14 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambiente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiente',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Cliente'),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='ip',
            field=models.CharField(blank=True, max_length=20, verbose_name='Endereço de IP'),
        ),
        migrations.CreateModel(
            name='Impressora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome da impressora no windows')),
                ('marca', models.CharField(choices=[('E', 'Epson'), ('B', 'Bematech'), ('G', 'Elgin'), ('D', 'Daruma'), ('O', 'Outros')], default='E', max_length=1)),
                ('modelo', models.CharField(blank=True, max_length=70, null=True)),
                ('setor', models.CharField(choices=[('E', 'Caixa'), ('B', 'Cozinha'), ('G', 'Bar'), ('D', 'Cafeteria'), ('O', 'Salão')], default='E', max_length=1)),
                ('ip', models.CharField(blank=True, max_length=20, verbose_name='Endereço de IP')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambiente.ambiente')),
            ],
            options={
                'verbose_name': 'Impressora',
                'verbose_name_plural': 'Impressoras',
            },
        ),
    ]
