# Generated by Django 4.0.6 on 2022-07-06 15:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_motivo', models.CharField(max_length=255, verbose_name='Motivo da Visita')),
            ],
        ),
        migrations.CreateModel(
            name='Trajeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saida', models.CharField(max_length=255, verbose_name='Saída')),
                ('destino', models.CharField(max_length=255, verbose_name='Destino')),
                ('kilometragem', models.FloatField(verbose_name='Kms')),
                ('data_visita', models.DateTimeField(verbose_name='Data da visita')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('descricao', models.TextField(blank=True)),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trajetos.motivo')),
            ],
        ),
    ]
